use64
vmread rax, rax
vmread rax, rcx
vmread rax, rdx
vmread rax, rbx
vmread rax, rsp
vmread rax, rbp
vmread rax, rsi
vmread rax, rdi
vmread rcx, rax
vmread rcx, rcx
vmread rcx, rdx
vmread rcx, rbx
vmread rcx, rsp
vmread rcx, rbp
vmread rcx, rsi
vmread rcx, rdi
vmread rdx, rax
vmread rdx, rcx
vmread rdx, rdx
vmread rdx, rbx
vmread rdx, rsp
vmread rdx, rbp
vmread rdx, rsi
vmread rdx, rdi
vmread rbx, rax
vmread rbx, rcx
vmread rbx, rdx
vmread rbx, rbx
vmread rbx, rsp
vmread rbx, rbp
vmread rbx, rsi
vmread rbx, rdi
vmread rsp, rax
vmread rsp, rcx
vmread rsp, rdx
vmread rsp, rbx
vmread rsp, rsp
vmread rsp, rbp
vmread rsp, rsi
vmread rsp, rdi
vmread rbp, rax
vmread rbp, rcx
vmread rbp, rdx
vmread rbp, rbx
vmread rbp, rsp
vmread rbp, rbp
vmread rbp, rsi
vmread rbp, rdi
vmread rsi, rax
vmread rsi, rcx
vmread rsi, rdx
vmread rsi, rbx
vmread rsi, rsp
vmread rsi, rbp
vmread rsi, rsi
vmread rsi, rdi
vmread rdi, rax
vmread rdi, rcx
vmread rdi, rdx
vmread rdi, rbx
vmread rdi, rsp
vmread rdi, rbp
vmread rdi, rsi
vmread rdi, rdi
