use64
vmwrite eax, eax
vmwrite eax, ecx
vmwrite eax, edx
vmwrite eax, ebx
vmwrite eax, esp
vmwrite eax, ebp
vmwrite eax, esi
vmwrite eax, edi
vmwrite ecx, eax
vmwrite ecx, ecx
vmwrite ecx, edx
vmwrite ecx, ebx
vmwrite ecx, esp
vmwrite ecx, ebp
vmwrite ecx, esi
vmwrite ecx, edi
vmwrite edx, eax
vmwrite edx, ecx
vmwrite edx, edx
vmwrite edx, ebx
vmwrite edx, esp
vmwrite edx, ebp
vmwrite edx, esi
vmwrite edx, edi
vmwrite ebx, eax
vmwrite ebx, ecx
vmwrite ebx, edx
vmwrite ebx, ebx
vmwrite ebx, esp
vmwrite ebx, ebp
vmwrite ebx, esi
vmwrite ebx, edi
vmwrite esp, eax
vmwrite esp, ecx
vmwrite esp, edx
vmwrite esp, ebx
vmwrite esp, esp
vmwrite esp, ebp
vmwrite esp, esi
vmwrite esp, edi
vmwrite ebp, eax
vmwrite ebp, ecx
vmwrite ebp, edx
vmwrite ebp, ebx
vmwrite ebp, esp
vmwrite ebp, ebp
vmwrite ebp, esi
vmwrite ebp, edi
vmwrite esi, eax
vmwrite esi, ecx
vmwrite esi, edx
vmwrite esi, ebx
vmwrite esi, esp
vmwrite esi, ebp
vmwrite esi, esi
vmwrite esi, edi
vmwrite edi, eax
vmwrite edi, ecx
vmwrite edi, edx
vmwrite edi, ebx
vmwrite edi, esp
vmwrite edi, ebp
vmwrite edi, esi
vmwrite edi, edi
