use64
vmwrite rax, rax
vmwrite rax, rcx
vmwrite rax, rdx
vmwrite rax, rbx
vmwrite rax, rsp
vmwrite rax, rbp
vmwrite rax, rsi
vmwrite rax, rdi
vmwrite rcx, rax
vmwrite rcx, rcx
vmwrite rcx, rdx
vmwrite rcx, rbx
vmwrite rcx, rsp
vmwrite rcx, rbp
vmwrite rcx, rsi
vmwrite rcx, rdi
vmwrite rdx, rax
vmwrite rdx, rcx
vmwrite rdx, rdx
vmwrite rdx, rbx
vmwrite rdx, rsp
vmwrite rdx, rbp
vmwrite rdx, rsi
vmwrite rdx, rdi
vmwrite rbx, rax
vmwrite rbx, rcx
vmwrite rbx, rdx
vmwrite rbx, rbx
vmwrite rbx, rsp
vmwrite rbx, rbp
vmwrite rbx, rsi
vmwrite rbx, rdi
vmwrite rsp, rax
vmwrite rsp, rcx
vmwrite rsp, rdx
vmwrite rsp, rbx
vmwrite rsp, rsp
vmwrite rsp, rbp
vmwrite rsp, rsi
vmwrite rsp, rdi
vmwrite rbp, rax
vmwrite rbp, rcx
vmwrite rbp, rdx
vmwrite rbp, rbx
vmwrite rbp, rsp
vmwrite rbp, rbp
vmwrite rbp, rsi
vmwrite rbp, rdi
vmwrite rsi, rax
vmwrite rsi, rcx
vmwrite rsi, rdx
vmwrite rsi, rbx
vmwrite rsi, rsp
vmwrite rsi, rbp
vmwrite rsi, rsi
vmwrite rsi, rdi
vmwrite rdi, rax
vmwrite rdi, rcx
vmwrite rdi, rdx
vmwrite rdi, rbx
vmwrite rdi, rsp
vmwrite rdi, rbp
vmwrite rdi, rsi
vmwrite rdi, rdi
