use64
; ------------------------------------------------------------------------------
; opcode xmm,xmm
; ------------------------------------------------------------------------------
movhlps xmm0, xmm0
movhlps xmm0, xmm1
movhlps xmm0, xmm2
movhlps xmm0, xmm3
movhlps xmm0, xmm4
movhlps xmm0, xmm5
movhlps xmm0, xmm6
movhlps xmm0, xmm7
movhlps xmm1, xmm0
movhlps xmm1, xmm1
movhlps xmm1, xmm2
movhlps xmm1, xmm3
movhlps xmm1, xmm4
movhlps xmm1, xmm5
movhlps xmm1, xmm6
movhlps xmm1, xmm7
movhlps xmm2, xmm0
movhlps xmm2, xmm1
movhlps xmm2, xmm2
movhlps xmm2, xmm3
movhlps xmm2, xmm4
movhlps xmm2, xmm5
movhlps xmm2, xmm6
movhlps xmm2, xmm7
movhlps xmm3, xmm0
movhlps xmm3, xmm1
movhlps xmm3, xmm2
movhlps xmm3, xmm3
movhlps xmm3, xmm4
movhlps xmm3, xmm5
movhlps xmm3, xmm6
movhlps xmm3, xmm7
movhlps xmm4, xmm0
movhlps xmm4, xmm1
movhlps xmm4, xmm2
movhlps xmm4, xmm3
movhlps xmm4, xmm4
movhlps xmm4, xmm5
movhlps xmm4, xmm6
movhlps xmm4, xmm7
movhlps xmm5, xmm0
movhlps xmm5, xmm1
movhlps xmm5, xmm2
movhlps xmm5, xmm3
movhlps xmm5, xmm4
movhlps xmm5, xmm5
movhlps xmm5, xmm6
movhlps xmm5, xmm7
movhlps xmm6, xmm0
movhlps xmm6, xmm1
movhlps xmm6, xmm2
movhlps xmm6, xmm3
movhlps xmm6, xmm4
movhlps xmm6, xmm5
movhlps xmm6, xmm6
movhlps xmm6, xmm7
movhlps xmm7, xmm0
movhlps xmm7, xmm1
movhlps xmm7, xmm2
movhlps xmm7, xmm3
movhlps xmm7, xmm4
movhlps xmm7, xmm5
movhlps xmm7, xmm6
movhlps xmm7, xmm7

