use64
; ------------------------------------------------------------------------------
; opcode xmm,xmm
; ------------------------------------------------------------------------------
movlhps xmm0, xmm0
movlhps xmm0, xmm1
movlhps xmm0, xmm2
movlhps xmm0, xmm3
movlhps xmm0, xmm4
movlhps xmm0, xmm5
movlhps xmm0, xmm6
movlhps xmm0, xmm7
movlhps xmm1, xmm0
movlhps xmm1, xmm1
movlhps xmm1, xmm2
movlhps xmm1, xmm3
movlhps xmm1, xmm4
movlhps xmm1, xmm5
movlhps xmm1, xmm6
movlhps xmm1, xmm7
movlhps xmm2, xmm0
movlhps xmm2, xmm1
movlhps xmm2, xmm2
movlhps xmm2, xmm3
movlhps xmm2, xmm4
movlhps xmm2, xmm5
movlhps xmm2, xmm6
movlhps xmm2, xmm7
movlhps xmm3, xmm0
movlhps xmm3, xmm1
movlhps xmm3, xmm2
movlhps xmm3, xmm3
movlhps xmm3, xmm4
movlhps xmm3, xmm5
movlhps xmm3, xmm6
movlhps xmm3, xmm7
movlhps xmm4, xmm0
movlhps xmm4, xmm1
movlhps xmm4, xmm2
movlhps xmm4, xmm3
movlhps xmm4, xmm4
movlhps xmm4, xmm5
movlhps xmm4, xmm6
movlhps xmm4, xmm7
movlhps xmm5, xmm0
movlhps xmm5, xmm1
movlhps xmm5, xmm2
movlhps xmm5, xmm3
movlhps xmm5, xmm4
movlhps xmm5, xmm5
movlhps xmm5, xmm6
movlhps xmm5, xmm7
movlhps xmm6, xmm0
movlhps xmm6, xmm1
movlhps xmm6, xmm2
movlhps xmm6, xmm3
movlhps xmm6, xmm4
movlhps xmm6, xmm5
movlhps xmm6, xmm6
movlhps xmm6, xmm7
movlhps xmm7, xmm0
movlhps xmm7, xmm1
movlhps xmm7, xmm2
movlhps xmm7, xmm3
movlhps xmm7, xmm4
movlhps xmm7, xmm5
movlhps xmm7, xmm6
movlhps xmm7, xmm7

