use64
; ------------------------------------------------------------------------------
; opcode ax
; ------------------------------------------------------------------------------
fnstsw ax

; ------------------------------------------------------------------------------
; opcode m16
; ------------------------------------------------------------------------------
fnstsw word [rip + 0x13]
fnstsw word [rip + 0x1235]
fnstsw word [rip + 0x12345679]
fnstsw word [rbx]
fnstsw word [rcx + 0x14]
fnstsw word [rdx + 0x15]
fnstsw word [rbx + 0x1235]
fnstsw word [rbx + 0x12345679]
fnstsw word [rbx + rcx]
fnstsw word [rbx + 4 * rcx]
fnstsw word [rbx + rcx + 0x13]
fnstsw word [rbx + rcx + 0x1235]
fnstsw word [rbx + rcx + 0x12345679]
fnstsw word [rbx + 4 * rcx + 0x13]
fnstsw word [rbx + 4 * rcx + 0x1235]
fnstsw word [rbx + 8 * rcx + 0x12345679]
fnstsw word [4 * rcx]
fnstsw word [4 * rcx + 0x13]
fnstsw word [4 * rcx + 0x1235]
fnstsw word [4 * rcx + 0x12345679]
fnstsw word [rbp]
fnstsw word [rbp + 0x12]
fnstsw word [rbp + 0x1234]
fnstsw word [rbp + 0x12345678]
fnstsw word [4 * rbp]
fnstsw word [4 * rbp + 0x12]
fnstsw word [4 * rbp + 0x1234]
fnstsw word [4 * rbp + 0x12345678]
fnstsw word [rbx + 4 * rbp]
fnstsw word [rbx + 4 * rbp + 0x12]
fnstsw word [rbx + 4 * rbp + 0x1234]
fnstsw word [rbx + 4 * rbp + 0x12345678]
fnstsw word [rsp]
fnstsw word [rsp + 0x12]
fnstsw word [rsp + 0x1234]
fnstsw word [rsp + 0x12345678]
fnstsw word [rsp + rax]
fnstsw word [rsp + rbp]
fnstsw word [rsp + 2*rbp]
fnstsw word [rsp + 4*rbp]
fnstsw word [rsp + 8*rbp]
fnstsw word [rax]
fnstsw word [rcx]
fnstsw word [rdx]
fnstsw word [rbx]
fnstsw word [rsp]
fnstsw word [rbp]
fnstsw word [rsi]
fnstsw word [rdi]
fnstsw word [rax + 2*rax]
fnstsw word [rcx + 2*rcx]
fnstsw word [rdx + 2*rdx]
fnstsw word [rbx + 2*rbx]
fnstsw word [rbp + 2*rbp]
fnstsw word [rsi + 2*rsi]
fnstsw word [rdi + 2*rdi]

