use64
movsxd rax, eax
movsxd rax, ecx
movsxd rax, edx
movsxd rax, ebx
movsxd rax, esp
movsxd rax, ebp
movsxd rax, esi
movsxd rax, edi
movsxd rcx, eax
movsxd rcx, ecx
movsxd rcx, edx
movsxd rcx, ebx
movsxd rcx, esp
movsxd rcx, ebp
movsxd rcx, esi
movsxd rcx, edi
movsxd rdx, eax
movsxd rdx, ecx
movsxd rdx, edx
movsxd rdx, ebx
movsxd rdx, esp
movsxd rdx, ebp
movsxd rdx, esi
movsxd rdx, edi
movsxd rbx, eax
movsxd rbx, ecx
movsxd rbx, edx
movsxd rbx, ebx
movsxd rbx, esp
movsxd rbx, ebp
movsxd rbx, esi
movsxd rbx, edi
movsxd rsp, eax
movsxd rsp, ecx
movsxd rsp, edx
movsxd rsp, ebx
movsxd rsp, esp
movsxd rsp, ebp
movsxd rsp, esi
movsxd rsp, edi
movsxd rbp, eax
movsxd rbp, ecx
movsxd rbp, edx
movsxd rbp, ebx
movsxd rbp, esp
movsxd rbp, ebp
movsxd rbp, esi
movsxd rbp, edi
movsxd rsi, eax
movsxd rsi, ecx
movsxd rsi, edx
movsxd rsi, ebx
movsxd rsi, esp
movsxd rsi, ebp
movsxd rsi, esi
movsxd rsi, edi
movsxd rdi, eax
movsxd rdi, ecx
movsxd rdi, edx
movsxd rdi, ebx
movsxd rdi, esp
movsxd rdi, ebp
movsxd rdi, esi
movsxd rdi, edi
