use64
; ------------------------------------------------------------------------------
; opcode r32,mm
; ------------------------------------------------------------------------------
pmovmskb eax, mm0
pmovmskb eax, mm1
pmovmskb eax, mm2
pmovmskb eax, mm3
pmovmskb eax, mm4
pmovmskb eax, mm5
pmovmskb eax, mm6
pmovmskb eax, mm7
pmovmskb ecx, mm0
pmovmskb ecx, mm1
pmovmskb ecx, mm2
pmovmskb ecx, mm3
pmovmskb ecx, mm4
pmovmskb ecx, mm5
pmovmskb ecx, mm6
pmovmskb ecx, mm7
pmovmskb edx, mm0
pmovmskb edx, mm1
pmovmskb edx, mm2
pmovmskb edx, mm3
pmovmskb edx, mm4
pmovmskb edx, mm5
pmovmskb edx, mm6
pmovmskb edx, mm7
pmovmskb ebx, mm0
pmovmskb ebx, mm1
pmovmskb ebx, mm2
pmovmskb ebx, mm3
pmovmskb ebx, mm4
pmovmskb ebx, mm5
pmovmskb ebx, mm6
pmovmskb ebx, mm7
pmovmskb esp, mm0
pmovmskb esp, mm1
pmovmskb esp, mm2
pmovmskb esp, mm3
pmovmskb esp, mm4
pmovmskb esp, mm5
pmovmskb esp, mm6
pmovmskb esp, mm7
pmovmskb ebp, mm0
pmovmskb ebp, mm1
pmovmskb ebp, mm2
pmovmskb ebp, mm3
pmovmskb ebp, mm4
pmovmskb ebp, mm5
pmovmskb ebp, mm6
pmovmskb ebp, mm7
pmovmskb esi, mm0
pmovmskb esi, mm1
pmovmskb esi, mm2
pmovmskb esi, mm3
pmovmskb esi, mm4
pmovmskb esi, mm5
pmovmskb esi, mm6
pmovmskb esi, mm7
pmovmskb edi, mm0
pmovmskb edi, mm1
pmovmskb edi, mm2
pmovmskb edi, mm3
pmovmskb edi, mm4
pmovmskb edi, mm5
pmovmskb edi, mm6
pmovmskb edi, mm7

; ------------------------------------------------------------------------------
; opcode r64,mm
; ------------------------------------------------------------------------------
pmovmskb rax, mm0
pmovmskb rax, mm1
pmovmskb rax, mm2
pmovmskb rax, mm3
pmovmskb rax, mm4
pmovmskb rax, mm5
pmovmskb rax, mm6
pmovmskb rax, mm7
pmovmskb rcx, mm0
pmovmskb rcx, mm1
pmovmskb rcx, mm2
pmovmskb rcx, mm3
pmovmskb rcx, mm4
pmovmskb rcx, mm5
pmovmskb rcx, mm6
pmovmskb rcx, mm7
pmovmskb rdx, mm0
pmovmskb rdx, mm1
pmovmskb rdx, mm2
pmovmskb rdx, mm3
pmovmskb rdx, mm4
pmovmskb rdx, mm5
pmovmskb rdx, mm6
pmovmskb rdx, mm7
pmovmskb rbx, mm0
pmovmskb rbx, mm1
pmovmskb rbx, mm2
pmovmskb rbx, mm3
pmovmskb rbx, mm4
pmovmskb rbx, mm5
pmovmskb rbx, mm6
pmovmskb rbx, mm7
pmovmskb rsp, mm0
pmovmskb rsp, mm1
pmovmskb rsp, mm2
pmovmskb rsp, mm3
pmovmskb rsp, mm4
pmovmskb rsp, mm5
pmovmskb rsp, mm6
pmovmskb rsp, mm7
pmovmskb rbp, mm0
pmovmskb rbp, mm1
pmovmskb rbp, mm2
pmovmskb rbp, mm3
pmovmskb rbp, mm4
pmovmskb rbp, mm5
pmovmskb rbp, mm6
pmovmskb rbp, mm7
pmovmskb rsi, mm0
pmovmskb rsi, mm1
pmovmskb rsi, mm2
pmovmskb rsi, mm3
pmovmskb rsi, mm4
pmovmskb rsi, mm5
pmovmskb rsi, mm6
pmovmskb rsi, mm7
pmovmskb rdi, mm0
pmovmskb rdi, mm1
pmovmskb rdi, mm2
pmovmskb rdi, mm3
pmovmskb rdi, mm4
pmovmskb rdi, mm5
pmovmskb rdi, mm6
pmovmskb rdi, mm7

